// Products
export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED";
export const PRODUCT_FETACHED = "PRODUCT_FETACHED";

// Auth
export const USER_LOGGEDIN = "USER_LOGGEDIN";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
